package com.datakata.ingest

import com.datakata.config.AppConfig
import org.apache.kafka.clients.producer.{KafkaProducer, ProducerRecord}
import org.slf4j.LoggerFactory

import java.io.File
import java.time.LocalDate
import java.util.Properties
import scala.io.Source

/**
 * Reads daily CSV files generated by GenerateFiles from the filesystem source directory
 * and publishes each row to the `sales.filesystem` Kafka topic.
 *
 * Replaces ingestion/kafka_producer_files.py
 *
 * Note: reads the _flat_ CSV files written by Spark (part-*.csv inside each date folder).
 */
object FileSystemProducer {

  private val log    = LoggerFactory.getLogger(getClass)
  private val config = AppConfig()
  private val TOPIC  = "sales.filesystem"

  def main(args: Array[String]): Unit = {
    log.info(s"Starting filesystem ingestion → $TOPIC")

    val producer   = buildProducer()
    var totalCount = 0

    val start = LocalDate.parse(config.dataStartDate)
    val end   = LocalDate.parse(config.dataEndDate)

    var date = start
    while (!date.isAfter(end)) {
      val csvDir = new File(s"${config.fsDataDir}/csv/sales_$date")
      val csvFiles = Option(csvDir.listFiles())
        .map(_.filter(f => f.getName.startsWith("part-") && f.getName.endsWith(".csv")))
        .getOrElse(Array.empty[File])

      if (csvFiles.isEmpty) {
        log.warn(s"No CSV found for $date in ${csvDir.getAbsolutePath}")
      } else {
        csvFiles.foreach { file =>
          val count = processFile(file, date.toString, producer)
          totalCount += count
          log.info(s"$date: published $count rows from ${file.getName}")
        }
      }
      date = date.plusDays(1)
    }

    producer.flush()
    producer.close()
    log.info(s"Filesystem ingestion complete — $totalCount records sent to $TOPIC")
  }

  private def processFile(file: File, date: String,
                           producer: KafkaProducer[String, String]): Int = {
    val src     = Source.fromFile(file, "UTF-8")
    val lines   = src.getLines().toSeq
    src.close()

    if (lines.isEmpty) return 0

    val header = lines.head.split(",").map(_.trim)
    var count  = 0

    lines.tail.foreach { line =>
      val values = splitCsvLine(line)
      if (values.length == header.length) {
        val fields = header.zip(values).toMap
        val json   = mapToJson(fields, date)
        val key    = s"$date-$count"
        producer.send(new ProducerRecord[String, String](TOPIC, key, json))
        count += 1
      }
    }
    count
  }

  /** Handles quoted fields with commas inside. */
  private def splitCsvLine(line: String): Array[String] = {
    val result  = scala.collection.mutable.ArrayBuffer[String]()
    val current = new StringBuilder
    var inQuote = false
    line.foreach {
      case '"'                    => inQuote = !inQuote
      case ',' if !inQuote        => result += current.toString(); current.clear()
      case c                      => current += c
    }
    result += current.toString()
    result.toArray
  }

  private def mapToJson(f: Map[String, String], date: String): String = {
    def esc(k: String) = "\"" + f.getOrElse(k, "").replace("\"", "\\\"") + "\""
    def num(k: String) = {
      val v = f.getOrElse(k, "")
      if (v.isEmpty) "null" else v
    }
    s"""{"sale_id":null,"sale_date":${esc("sale_date")},"salesman_id":${num("salesman_id")},""" +
    s""""salesman_name":${esc("salesman_name")},"product_id":${num("product_id")},""" +
    s""""product_name":${esc("product_name")},"category":${esc("category")},""" +
    s""""city":${esc("city")},"state":${esc("state")},"region":${esc("region")},""" +
    s""""quantity":${num("quantity")},"unit_price":${num("unit_price")},""" +
    s""""total_amount":${num("total_amount")},"source":"filesystem"}"""
  }

  private def buildProducer(): KafkaProducer[String, String] = {
    val props = new Properties()
    props.put("bootstrap.servers",  config.kafkaServers)
    props.put("key.serializer",   "org.apache.kafka.common.serialization.StringSerializer")
    props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer")
    props.put("acks", "1")
    new KafkaProducer[String, String](props)
  }
}
